version: "3"

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    restart: always
    volumes:
      - ./client:/data
      - /data/node_modules
    environment:
      - API_URL=http://localhost:8081/
      - WATCHPACK_POLLING=true
    container_name: client

  server:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    restart: always
    volumes:
      - ./:/data
      - /data/node_modules
    depends_on:
      - server-database
    environment:
      - DATABASE_URL=server-database:27017
    container_name: server

  server-database:
    build: ./mongo
    ports:
      - 27017:27017
    restart: always
    volumes:
      - /data/db
    container_name: database
    environment:
      #MONGO_INITDB_ROOT_USERNAME: {{USERNAME}}
      #MONGO_INITDB_ROOT_PASSWORD: {{PWD}}
      MONGO_INITDB_DATABASE: articles
