version: "3.8"

services:
  server:
    environment:
      - DOTENV=

  postgres-keycloak:
    image: postgres:15
    expose:
      - "5432"
    ports:
      - "25432:5432"
    restart: always
    volumes:
      - keycloak-db-data:/var/lib/postgresql/data
    container_name: postgres-keycloak
    networks:
      - your-network
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: changeMe
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    volumes:
      - ./nginx/default-keycloak.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - keycloak

  keycloak:
    container_name: keycloak-container
    image: quay.io/keycloak/keycloak:21.1
    # prettier-ignore
    entrypoint:
      [
        "/opt/keycloak/bin/kc.sh",
        "start-dev",
        "--import-realm",
        "--proxy=passthrough",
        "--db=postgres",
      ]
    volumes:
      - ./keycloak/myrealm.json:/opt/keycloak/data/import/myrealm.json
    environment:
      KC_DB: keycloak
      KC_DB_URL: "jdbc:postgresql://postgres-keycloak/keycloak"
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: changeMe
      KC_DB_SCHEMA: public
      #KC_HOSTNAME: "localhost"
      KC_HOSTNAME_STRICT_HTTPS: false
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
      KC_TRANSACTION_XA_ENABLED: false
      KC_HOSTNAME_STRICT: false
      KC_HTTP_ENABLED: true
      KC_PROXY_ADDRESS_FORWARDING: true
      #KC_HOSTNAME_PORT: 9080
      KC_PROXY: passthrough
      #KC_HTTP_RELATIVE_PATH: /keycloak
      KC_HOSTNAME_STRICT_BACKCHANNEL: false
      HTTP_ADDRESS_FORWARDING: true
    ports:
      - 9080:8080
    networks:
      - your-network
    depends_on:
      postgres-keycloak:
        condition: service_healthy

volumes:
  keycloak-db-data:
    driver: local
