apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app: mxms-ingress
  ports:
    - name: kibana-port
      protocol: TCP
      port: 443
      targetPort: 443

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mxms-ingress
  template:
    metadata:
      labels:
        app: mxms-ingress
    spec:
      containers:
        - name: nginx
          image: {{NGINX_IMAGE_WITH_TAG}}
          ports:
            - containerPort: 443
